---

- name: Set alias {{ valias.email }} facts
  set_fact:
    alias_email: "{{ valias.email }}"
    alias_dest: "{{ valias.dest|default('')|replace(',', ' ')|replace(';', ' ') if valias.dest|default('') is string else valias.dest|join(' ') }}"
    alias_state: "{{ valias.state|default('present') }}"

- name: Get current state of alias {{ alias_email }}
  command: "redis-cli -n {{ vmail_redis_db }} smembers aliases:{{ alias_email }}"
  register: alias_in_db

- name: Add alias {{ alias_email }} if needed
  command: "redis-cli -n {{ vmail_redis_db }} sadd aliases:{{ alias_email }} {{ alias_dest }}"
  when:
    - domain_state == 'present'
    - alias_state == 'present'
    - alias_dest|length > 0

- name: Cleanup alias {{ alias_email }} if needed
  command: "redis-cli -n {{ vmail_redis_db }} srem aliases:{{ alias_email }} {{ alias_in_db.stdout_lines|difference(alias_dest.split(' '))|join(' ') }}"
  when:
    - domain_state == 'present'
    - alias_state == 'present'
    - alias_dest|length > 0
    - alias_in_db.stdout_lines|length > 0
    - "alias_in_db.stdout_lines|difference(alias_dest.split(' '))|length > 0"

- name: Remove alias {{ alias_email }} if needed
  command: "redis-cli -n {{ vmail_redis_db }} del aliases:{{ alias_email }}"
  when:
    - domain_state == 'absent' or alias_state == 'absent' or not alias_dest
