---

- name: Set user {{ vuser.email }} facts
  set_fact:
    user_email: "{{ vuser.email }}"
    user_password: "{{ vuser.password|default('') }}"
    user_encrypted_password: "{{ vuser.encrypted_password|default('') }}"
    user_maildir: "{{ vmail_path }}/{{ domain_name }}/{{ vuser.email }}"
    user_maildir_mode: "{{ vmail_path_mode }}"
    user_uid: "{{ vmail_user.uid }}"
    user_gid: "{{ vmail_user.group }}"
    user_state: "{{ vuser.state|default('present') }}"
    user_uuid: "{{ vuser.email|to_uuid }}"

- name: Encrypt password for {{ user_email }} if needed
  shell:
    cmd: encrypt -p
    stdin: "{{ user_password }}\n"
  register: encrypted_password
  when:
    - not user_encrypted_password
    - domain_state == 'present'
    - user_state == 'present'

- name: Set encrypted password fact for {{ user_email }} if needed
  set_fact:
    user_encrypted_password: "{{ encrypted_password.stdout|trim }}"
  when:
    - not user_encrypted_password
    - domain_state == 'present'
    - user_state == 'present'

- name: Ensure maildir directory for {{ user_email }} exists
  file:
    path: "{{ user_maildir }}"
    state: directory
    mode: "{{ user_maildir_mode }}"
    owner: "{{ user_uid }}"
    group: "{{ user_gid }}"
  when:
    - domain_state == 'present'
    - user_state == 'present'

- name: Add {{ user_email }} to mailaddr table if needed
  command: "redis-cli -n {{ vmail_redis_db }} sadd mailaddr {{ user_email }}"
  when:
    - domain_state == 'present'
    - user_state == 'present'

- name: Remove {{ user_email }} from mailaddr table if needed
  command: "redis-cli -n {{ vmail_redis_db }} srem mailaddr {{ user_email }}"
  when:
    - domain_state == 'absent' or user_state == 'absent'

- name: Add {{ user_email }} userinfo record if needed
  command: "redis-cli -n {{ vmail_redis_db }} hset user:{{ user_email }} uid {{ user_uid }} gid {{ user_gid }} maildir {{ user_maildir }} login {{ user_email }} passwd {{ user_encrypted_password }} uuid {{ user_uuid }}"
  when:
    - domain_state == 'present'
    - user_state == 'present'

- name: Remove {{ user_email }} userinfo record if needed
  command: "redis-cli -n {{ vmail_redis_db }} del user:{{ user_email }}"
  when:
    - domain_state == 'absent' or user_state == 'absent'
