---

- name: Configure root account email alias
  lineinfile:
    path: /etc/mail/aliases
    state: present
    line: "root: {{ postmaster }}"
    regexp: "^root"
  notify:
    - rebuild aliases

- name: Add virtual mail user account
  user:
    name: "{{ vmail_username }}"
    group: "{{ vmail_group }}"
    shell: "/sbin/nologin"
    home: "{{ vmail_path }}"
    create_home: no
  register: vmail_user

- name: Ensure home directory for virtual mail user account exists
  file:
    path: "{{ vmail_path }}"
    state: directory
    mode: "{{ vmail_path_mode }}"
    owner: "{{ vmail_username }}"
    group: "{{ vmail_group }}"

- name: Copy vmail.sql script to load virtual users
  template:
    src: vmail.sql.j2
    dest: /etc/mail/vmail.sql
    mode: 0640
    owner: root
    group: wheel

- name: Create new sqlite3 database file containing virtual users
  shell: "sqlite3 {{ vmail_sqlite_db_path }}.ng </etc/mail/vmail.sql"

- name: Update sqlite3 database file containing virtual users
  copy:
    src: "{{ vmail_sqlite_db_path }}.ng"
    dest: "{{ vmail_sqlite_db_path }}"
    remote_src: yes
    mode: 0644
    owner: root
    group: wheel
  notify:
    - restart smtpd

- name: Remove temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/mail/vmail.sql"
    - "{{ vmail_sqlite_db_path }}.ng"
